######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 6 23:35:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edge.h graphwidget.h node.h
SOURCES += edge.cpp graphwidget.cpp main.cpp node.cpp
